//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADV.Web.App_LocalResources.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla non magna eu leo placerat accumsan. Maecenas cursus augue id tincidunt sagittis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla non magna eu leo placerat accumsan. Maecenas cursus augue id tincidunt sagittis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla non magna eu leo placerat accumsan. Maecenas cursus augue id tincidunt sagittis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla non magna eu leo  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AboutMyself {
            get {
                return ResourceManager.GetString("AboutMyself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional education.
        /// </summary>
        public static string AdditionalEdu {
            get {
                return ResourceManager.GetString("AdditionalEdu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NN, Russia.
        /// </summary>
        public static string AddressVal {
            get {
                return ResourceManager.GetString("AddressVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth.
        /// </summary>
        public static string BDate {
            get {
                return ResourceManager.GetString("BDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January 1, 1990.
        /// </summary>
        public static string BDateVal {
            get {
                return ResourceManager.GetString("BDateVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dec.
        /// </summary>
        public static string Dec {
            get {
                return ResourceManager.GetString("Dec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer.
        /// </summary>
        public static string Developer {
            get {
                return ResourceManager.GetString("Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead developer.
        /// </summary>
        public static string DeveloperLead {
            get {
                return ResourceManager.GetString("DeveloperLead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doe Company.
        /// </summary>
        public static string DoeCompany {
            get {
                return ResourceManager.GetString("DoeCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla non magna eu leo placerat accumsan. Maecenas cursus augue id tincidunt sagittis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla non magna eu leo placerat accumsan..
        /// </summary>
        public static string DoeCompanyDesc {
            get {
                return ResourceManager.GetString("DoeCompanyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        public static string Education {
            get {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State University.
        /// </summary>
        public static string EduHigh {
            get {
                return ResourceManager.GetString("EduHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postgraduate degree.
        /// </summary>
        public static string EduPHD {
            get {
                return ResourceManager.GetString("EduPHD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degree work: Mathematical and Computer Modelling..
        /// </summary>
        public static string EduPHDDesc {
            get {
                return ResourceManager.GetString("EduPHDDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string EduPhdStatus {
            get {
                return ResourceManager.GetString("EduPhdStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary and Secondary school.
        /// </summary>
        public static string EduSchool {
            get {
                return ResourceManager.GetString("EduSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School..
        /// </summary>
        public static string EduSchoolDesc {
            get {
                return ResourceManager.GetString("EduSchoolDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alumnus.
        /// </summary>
        public static string EduSchoolStatus {
            get {
                return ResourceManager.GetString("EduSchoolStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State University, Faculty of Computational Mathematics and Cybernetics.
        /// </summary>
        public static string EduUniver {
            get {
                return ResourceManager.GetString("EduUniver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degree work: Mathematical and Computer Modelling..
        /// </summary>
        public static string EduUniverDesc {
            get {
                return ResourceManager.GetString("EduUniverDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alumnus (Specialist).
        /// </summary>
        public static string EduUniverStatus {
            get {
                return ResourceManager.GetString("EduUniverStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience.
        /// </summary>
        public static string Experience {
            get {
                return ResourceManager.GetString("Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feb.
        /// </summary>
        public static string Feb {
            get {
                return ResourceManager.GetString("Feb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to intermediate.
        /// </summary>
        public static string Intermediate {
            get {
                return ResourceManager.GetString("Intermediate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jan.
        /// </summary>
        public static string Jan {
            get {
                return ResourceManager.GetString("Jan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to John Doe.
        /// </summary>
        public static string JD {
            get {
                return ResourceManager.GetString("JD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to John Company.
        /// </summary>
        public static string JohnCompany {
            get {
                return ResourceManager.GetString("JohnCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla non magna eu leo placerat accumsan. Maecenas cursus augue id tincidunt sagittis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla non magna eu leo placerat accumsan..
        /// </summary>
        public static string JohnCompanyDesc {
            get {
                return ResourceManager.GetString("JohnCompanyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurs.
        /// </summary>
        public static string Kurs {
            get {
                return ResourceManager.GetString("Kurs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction to Probability and Statistics for Engineers.
        /// </summary>
        public static string Kurs1 {
            get {
                return ResourceManager.GetString("Kurs1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla non magna eu leo placerat accumsan. Maecenas cursus augue id tincidunt sagittis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla non magna eu leo placerat accumsan..
        /// </summary>
        public static string Kurs1Desc {
            get {
                return ResourceManager.GetString("Kurs1Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction to Scientific Computing.
        /// </summary>
        public static string Kurs2 {
            get {
                return ResourceManager.GetString("Kurs2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla non magna eu leo placerat accumsan. Maecenas cursus augue id tincidunt sagittis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla non magna eu leo placerat accumsan..
        /// </summary>
        public static string Kurs2Desc {
            get {
                return ResourceManager.GetString("Kurs2Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string MenuContacts {
            get {
                return ResourceManager.GetString("MenuContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience.
        /// </summary>
        public static string MenuExperience {
            get {
                return ResourceManager.GetString("MenuExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portfolio.
        /// </summary>
        public static string MenuPortfolio {
            get {
                return ResourceManager.GetString("MenuPortfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string MenuProfile {
            get {
                return ResourceManager.GetString("MenuProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        public static string MenuSkills {
            get {
                return ResourceManager.GetString("MenuSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to native.
        /// </summary>
        public static string Native {
            get {
                return ResourceManager.GetString("Native", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nizhniy Novgorod.
        /// </summary>
        public static string NN {
            get {
                return ResourceManager.GetString("NN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to current time.
        /// </summary>
        public static string Now {
            get {
                return ResourceManager.GetString("Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oct.
        /// </summary>
        public static string Oct {
            get {
                return ResourceManager.GetString("Oct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Info.
        /// </summary>
        public static string PersonalInfo {
            get {
                return ResourceManager.GetString("PersonalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portfolio.
        /// </summary>
        public static string Portfolio {
            get {
                return ResourceManager.GetString("Portfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        public static string Russian {
            get {
                return ResourceManager.GetString("Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senior Developer.
        /// </summary>
        public static string SeniorDeveloper {
            get {
                return ResourceManager.GetString("SeniorDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sep.
        /// </summary>
        public static string Sep {
            get {
                return ResourceManager.GetString("Sep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        public static string Skills {
            get {
                return ResourceManager.GetString("Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla non magna eu leo placerat accumsan..
        /// </summary>
        public static string Skills_DB {
            get {
                return ResourceManager.GetString("Skills_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit..
        /// </summary>
        public static string Skills_DevEnv {
            get {
                return ResourceManager.GetString("Skills_DevEnv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla non magna eu leo placerat accumsan..
        /// </summary>
        public static string Skills_Net {
            get {
                return ResourceManager.GetString("Skills_Net", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet..
        /// </summary>
        public static string Skills_Version {
            get {
                return ResourceManager.GetString("Skills_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla non magna eu leo placerat accumsan..
        /// </summary>
        public static string Skills_Web {
            get {
                return ResourceManager.GetString("Skills_Web", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Developer.
        /// </summary>
        public static string SoftwareDeveloperTitle {
            get {
                return ResourceManager.GetString("SoftwareDeveloperTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Lead.
        /// </summary>
        public static string TeamLead {
            get {
                return ResourceManager.GetString("TeamLead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeline.
        /// </summary>
        public static string Timeline {
            get {
                return ResourceManager.GetString("Timeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Experience.
        /// </summary>
        public static string WorkExperience {
            get {
                return ResourceManager.GetString("WorkExperience", resourceCulture);
            }
        }
    }
}
